version: '3.1'

services:

  db:
    image: postgres:13.3
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=clever_bank
      - TZ=Europe/Minsk
    ports:
      - '5432:5432'
    volumes:
      - ./init:/docker-entrypoint-initdb.d
